version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000

      # --- SMTP MAIL SETTINGS (GMAIL) ---
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=smtp.gmail.com
      - GITEA__mailer__SMTP_PORT=465
      - GITEA__mailer__USER=mariyababu675@gmail.com
      - GITEA__mailer__PASSWD=xxxxxxxxxxxxxxxx 
      - GITEA__mailer__FROM=mariyababu675@gmail.com
      - GITEA__mailer__TLS=true

      # --- DATABASE CONFIG (PostgreSQL) ---
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea123

    ports:
      - "3001:3000"
      - "223:22"
    volumes:
      - gitea_data:/data
    depends_on:
      - gitea_db

  gitea_db:
    image: postgres:15
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea123
      - POSTGRES_DB=gitea
    volumes:
      - gitea_db_data:/var/lib/postgresql/data

volumes:
  gitea_data:

  gitea_db_data:



